### ISSUE TITLE
Last annotated pdf viewer is not empty after logout and login

### ISSUE THREAD

**Issue by kaenova** [fanzru/web-anotasi-paper#42]
To reproduce:
1. Login
2. Upload paper
![image](https://user-images.githubusercontent.com/61568092/187618750-1840bf49-f64b-4c37-a193-95186638a550.png)
3. Logout
![image](https://user-images.githubusercontent.com/61568092/187618740-c46b1724-4b76-4f97-8631-62be5589a281.png)
4. Login
![image](https://user-images.githubusercontent.com/61568092/187618810-a29cf51c-e6da-4b12-b532-d6adfc39538c.png)

**Comment by fanzru** [comment]
fixed
